version: 2

builds:
- goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  main: ./cmd/travelgrunt/main.go
  ldflags:
  - -X main.appVersion={{.Version}}
  tags:
  - netgo
  - osusergo

brews:
- homepage: 'https://github.com/ivanilves/travelgrunt'
  description: 'cd inside [mono]repos without fatigue!'
  directory: Formula
  repository:
    owner: ivanilves
    name: homebrew-tap

archives:
- name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
  format: tar.gz

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
    - '^chore'
    - '^test'
    - '^style'
    - '^docs'
    - '^Merge pull request'
